services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  app:
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
  
  #mysql
  db:
    image: mysql:9.2
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=parole
      - MYSQL_DATABASE=docker-php
      - MYSQL_USER=user
      - MYSQL_PASSWORD=parole

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: parole

  #redis

volumes:
  mysqldata: